xdy/twodsix-foundryvtt

- package-lock.json
- package.json
- src/module/sheets/TwodsixActorSheet.ts
- static/styles/twodsix.css
- static/templates/actors/actor-sheet.html
- tsconfig.json
fix: Pulling Foundry types from NPM, updated tsconfig.json
fix: Added Kevin's CSS/Template changes
Style/feature
Character sheet styling wasn't done
Foundry types had to be installed locally
Progress on character sheet styling
Foundry types now part of NPM Install
Would need to do a new npm install
> New CSS, Foundry Types Updated

- src/module/settings.ts
- src/module/utils/parseUcf.ts
- src/module/utils/sheetUtils.ts
- static/templates/actors/actor-sheet.html
And, more testing of branch protection.
- [ x ] The commit message follows our guidelines
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)
Support for different modifiers for characteristic value of 0. (Different variants use different rules for this, all variants I know of use the formula "Math.floor((characteristic - 6) / 3)", but some then use a different value for a characteristic of 0.)
See above
See above
* **Does …
> refactor: Add support for different modifiers for characteristic value of 0.

- CHANGELOG.md
- package-lock.json
- package.json
- src/module/entities/TwodsixActor.ts
- static/styles/twodsix.css
- static/system.json
- static/template.json
- static/templates/actors/actor-sheet.html
> Updated Skill list modifiers and resetting modifier option window. All good, very happy!

- package-lock.json
- src/module/config.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixRolls.ts
- src/twodsix.ts
- static/templates/actors/parts/actor-skills.html
- static/templates/chat/roll-dialog.html
If you shift-click a skill a dialog where you can choose advantage/disadvantage, difficulty and modifiers show up.
> Issue #59 Add support for advantage/disadvantage

- package-lock.json
- src/module/migration.ts
- src/module/settings.ts
- src/twodsix.ts
Adds basic migration support, but no actual migrations.
> Issue #65 Added basic migration support

- package-lock.json
- package.json
- src/module/migration.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/twodsix.ts
- static/system.json
- webpack.config.ts
Also fixes migrations and includes the first migration (that sets data.name), does not migrate items on characters, only those in compendiums or the Items Directory.
> fix: Fixes issue #70 (the data.name field was not set)

- package-lock.json
- src/module/entities/TwodsixItem.ts
- src/module/migration.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/twodsix.ts
Reuses data.name as an example migration, though we really should just remove the field and use name instead.
> Fix: Fixes issue #101, migrating items that are on an actor.

- package-lock.json
- static/styles/twodsix.css
- static/system.json
- static/templates/actors/parts/actor/actor-info.html
- static/templates/items/parts/common-parts.html
Visual fixes CSS:
- Overall consistency changes
- Macro and Player configuration screen's visibility fix.
- Chat fixes
- Copy/Paste into textboxes font, colour and background hack to force uniform look.
- Various alignment changes.
- Damage colour brightness increased.
- Changed the character 'Info page'; smaller fields for Contacts, Allies and Enemies.
- Bio text field extends now instead of scroll-bar.
> Alpha0.6.21 visual adjustments

- CONTRIBUTING.md
- docs/docs.md
- package-lock.json
- src/module/handlebars.ts
- src/module/settings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixRolls.ts
- static/lang/en.json
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/chat/damage-message.html
> Restyle Resolves issue #121 -- Implements CE and CEL autofire rules.

- src/module/hooks/index.ts
- src/module/hooks/ready.ts
- src/module/utils/createItemMacro.ts
- src/module/utils/rollItemMacro.ts
- src/twodsix.ts
- webpack.config.ts
None
Same as before
Preparation to start using fvttdev once that's released.
I sure hope not. :)
n/a
> refactor: Preparation for using fvttdev.

- .gitignore
- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/renderSettingsConfig.ts
- src/module/migration.ts
- src/module/settings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- static/lang/de.json
- static/lang/en.json
- static/lang/es.json
- static/lang/sv.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/chat/throw-dialog.html
- static/templates/items/parts/common-parts.html
feature
untrained skills are currently handled in aspecial way.
This change makes it so that they are handled like other skills by creating an untrained skill on every actor.
Needs a migration
> fix: add untrained skill

- src/module/migration.ts
bug fix
migrations fail
Migrations hopefully  work. Also only adds untrained skill to travellers
No
> fix: fixes migrations for untrained skill

- src/module/hooks/updateHits.ts
bug fix
There is an issue with unlinked tokens that sometimes the code is trying to access data  which does not exist. It doesn't  hinder the functionality, but  it throws an error message.
This fix makes prevents this from happening. 
no
> fix: handle undefined values when giving damage

- src/module/handlebars.ts
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/actors/parts/ship/ship-storage.html
feature
Manual sorting which sometimes does not work.
add feature so that items gets sorted by name alphabetically automatically in character/ship sheets.
No
Fix #114
> WIP: fix: add feature to automatically sort items

- user_macros/NPC Parsers/Parser for CE 1001 Characters.js
added an "await" on main call that caused errors
> Update Parser for CE 1001 Characters.js

- user_macros/UWP Translator/UWP Translator.js
Truncated proper rollable table name
> Update UWP Translator.js

- user_macros/NPC Parsers/Parser for CL Character Generator v2.js
Fixed a compendium lookup error.
> Update Parser for CL Character Generator v2.js

- user_macros/NPC Parsers/2e Character Parser for traveller tools v4.js
Skill lookup only for item type=='skills'
> Update 2e Character Parser for traveller tools v4.js

- static/templates/actors/ship-sheet.html
Bug fix
There was a small typo in the ship sheet regarding maintenance cost which prevented new values from
being saved.
The maintenance cost gets saved
No
> Fix: small typo in the ship sheet

- user_macros/Healing Macros/FirstAid v0_8.js
- user_macros/Healing Macros/HealGMorPlayer v0_8.js
- user_macros/NPC Parsers/2e Character Parser for traveller tools v0_8.js
- user_macros/NPC Parsers/CL Character Importer v0_8.js
- user_macros/NPC Parsers/Parser for CE 1001 Characters v0_8.js
- user_macros/Trade Goods Generator/Generate Trade Table v0_8.js
- user_macros/UWP Translator/UPP Translator v0_8.js
- user_macros/Update Initiative/UpdateInitiative v0_8.js
- [X ] Docs have been added / updated (for bug fixes / features)
Adds new user macro files that are compatible with Foundry VTT ver 0.86
No compatible macros for new version of Foundry
Updated the macros to be compatible.
No
> Upload New macros for FVTT v0_8

- src/module/utils/actorDamage.ts
This is a bug fix for #531 .
Error is thrown when damage is dropped on actor when damage causes death.  Problem with toggledCondition call after upgrade to v0.8.
Works as expected, "skull" is overlaid on icon.  Also added to mark combatant as defeated if found.
No
> fix: eliminate bug with toggling condition on death

- src/module/settings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/twodsix.ts
- static/assets/actor/Interface-Overlay-1.svg
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
New character attribute: hero point (for compatibility with Cepheus Deluxe).
No such feature - manual tracking
Add a location on the traveller sheet to track
No
Please note that I have slightly modified the actor sheet to fit the new information.  Hopefully this works for everyone.
> add: add hero points to actor sheet

- src/module/hooks/updateHits.ts
- src/module/utils/actorDamage.ts
Fix of lazy coding on my part.
Damage can be change
Same
No
Just a coding style change.
> fix: clean up poor coding style

- static/styles/twodsix.css
* styling fix/bugfix
correct rendering in Firefox blue thin scroll bars that match the overall style.
No
> Styling fixes

- static/styles/twodsix.css
Bug fix: style problems on ship sheet
Text does not have correct background and is uncentered.
Better alignment and backgrounds.
No
> Fix style problems

- src/module/sheets/TwodsixShipSheet.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/ship/ship-finance.html
- static/templates/actors/ship-sheet.html
Feature: finance tab on ship sheet
No such tab
Adds new tab to ship sheet
No
> WIP: Add finance tab to ship sheet

- src/module/handlebars.ts
Bug fix
Errors caused and actor sheets won't open when rate of fire is null
system will accommodate null as an empty string
No
> fix: null rate of fire value

- gulpfile.js
- src/module/handlebars.ts
- src/module/settings.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix_basic.css
- static/system.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
- static/templates/actors/parts/actor/actor-characteristics-atom.html
- static/templates/actors/parts/actor/actor-characteristics.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/actors/ship-sheet.html
Adds alternative styling for system,
Only black...
Now have the option to use Foundry's default styling.
No
> feat: add foundry default styling option

- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix_basic.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-characteristics-table.html
Changes the Characteristic display when using FVTT default style
Characteristics are spread all over
Characteristics in clean table
No
> Table for characteristics when using FVTT default style

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-bgi-std.html
Adds radiation exposure to default actor sheet
No field on sheet
Adds field
No
> fix: add radiation exposure to default actor sheet

- src/module/sheets/AbstractTwodsixActorSheet.ts
Fix of encumbrance value
Value is float with multiple digits of precision - meaning the display can take up a lot of room.
Value rounded to nearest tenth.
No
> fix: round encumbrance value

- src/module/config.ts
- src/module/handlebars.ts
- src/module/settings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/actor/actor-characteristics-table.html
- static/templates/actors/parts/actor/actor-characteristics.html
- static/templates/chat/throw-dialog.html
- static/templates/items/skills-sheet.html
Feature: add 2 alternative skill characteristics instead of PSI - can be named in settings
Fixed characteristic names
Option to choose
NO
> feat: add alternative skill characteristics

- src/module/handlebars.ts
- src/module/settings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- static/styles/twodsix.css
Cleans up code when using abbreviated characteristic names and supports localization
Cleans up some redundant style entries in twodsix.css
Code redundant and localization not always used
Cleaner code and uses localization
No
> fix: cleanup coding

- user_macros/Cepheus Deluxe Wounds/applyWounds4.js
- user_macros/Planet Mapper/CepheusDeluxeGalaxyImporter.js
Adds two Cepheus Deluxe specific macros to the repository
Macros only on Discord
Macros on GitHub and Wiki updated
No
> fix: add CD specific macros

- src/module/settings.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/assets/actor/Interface-Tabs-left.svg
- static/assets/actor/Interface-Tabs-middle.svg
- static/assets/actor/Interface-Tabs-right.svg 
- static/styles/twodsix.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-characteristics.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
This is a branch for @marvin9257 so that he can continue the development of the dynamically styled actor sheets
> Start of dynamic actor sheets

- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/sheetUtils.ts
- static/styles/twodsix.css
Bug Fix
Fix styling issues for FVTT v9. default styles have alignment, color and background issues due to base FVTT style sheet being updated.
Style sheets revised to be nearly compatible.  Ship tab backgrounds are still not 100% 
No
> fix: update to new FVTT v9

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/sheets/TwodsixShipCrewPositionSheet.ts
- src/module/sheets/TwodsixShipV2Sheet.ts
- src/twodsix.ts
- src/types/twodsix.d.ts
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/ship_v2/ship-crew.html
- static/templates/actors/ship-sheet_v2.html
- static/templates/items/ship_crew_position-sheet.html
- static/templates/items/skills-sheet.html
> Ship crew positions

- src/module/sheets/TwodsixShipCrewPositionSheet.ts
- src/module/sheets/TwodsixShipV2Sheet.ts
- src/module/utils/TwodsixShipActions.ts
- src/twodsix.ts
- static/lang/en.json
- static/template.json
- static/templates/actors/parts/ship_v2/ship-crew.html
- static/templates/items/ship_crew_position-sheet.html
> feature: ship crew positions

- static/system.json
Bug Fix
Current compendium references in system.json use "entity" rather than "type" that FVTT v9 prefers
Make a secondary entry of type declaration
* No
> fix: update FVTT v9 compendium references

- src/module/AdvancedSettings.ts
bug fix
settings pages don't work for foundry V8
Should hopefully work :)
No
> fix: fixes a v8 bug with the new settings sub pages

- src/module/settings.ts
bug fix
previously the name was given as an initial value to the rulesets.
This change fixes that issue.
No
This is the last version which is compatible with foundry V8
> fix: initial value of ruleset settings

- src/module/utils/TwodsixDiceRoll.ts
Bug fix
An error was introduced when addying typing for how the effect is
calculated.
Adding brackets resolves the ambiguity issue.
no
> fix: wrongly calculated effect

- .github/workflows/test-release.yml
> Attempt at adding autmoatic discord posting

- static/styles/twodsix_basic.css
bug fix
Damage draggable  not outlined in color
Add color and highlighting to draggable
No
> WIP fix: color damage card

- .github/workflows/test-release.yml
- src/scripts/discord.sh
> hopefuly this fixes sending to discord

- src/scripts/discord.sh
> update to discord script

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/items/augment-sheet.html
bug fix
some alignment and format issues on item windows
clean-up several problems - all visual/display
No
> fix: style adjustments

- static/templates/actors/parts/actor/actor-info.html
bug fix
A bug was introduced in the 1.4.0 release hiding the notes section.
This commit fixes this issue.
No
> fix: bugfix for note section not showing in traveller sheet

- src/migration-utils.ts
- src/migrations/2022-01-03-06-15-30-merge-contacts.ts
- src/scripts/create-migration.mjs
> refactor: update to migration template and refactor some functions used in migrations

- static/styles/twodsix.css
bug fix
Ship tabs too small
Add some padding to the tab to make them larger
No
> fix: make tabs larger on ship sheet

- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/ship/ship-components-double.html
- static/templates/actors/parts/ship/ship-components-single.html
feature
Toggling component states must be done by opening up component sheet
Can click on the status icon and cycle the state
None
Addresses #808
> feat: toggle ship component states on component list

- .github/workflows/test-release.yml
- package.json
- rollup.config.js
- src/migrations/2022-01-03-06-15-30-merge-contacts.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipPositionSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/scripts/create-migration.mjs
- src/scripts/data_copy.mjs
- src/scripts/data_reset.mjs
- src/twodsix.ts
dev tooling
added tsc typechecking to the github workflow. It catches some things the eslint doesn't. 
No
> refactor: updated test workflow to include typechecking

- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
code clean up
Works fine
Still works
No
> fix: cleanup component state code

- static/styles/twodsix_moduleFix.css
Forced release to include prior merge #818 
> Feat: Add option to correct for certain style issues

- static/styles/twodsix_moduleFix.css
Feature - retry at release of #818 
Modules cause style clashes
Fix some more common clashes
No
> feat: Add experimental fix for module stlye issues

- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/ship-sheet.html
- static/templates/items/component-sheet.html
enhancement
misc issues existed on ship and component sheets
- replace total mass with displacement
- allow component weight to be designated as percentage of displacement
- add fades to component headers
- power components now list as power generated rather than power draw
No
> fix: small changes to ship and component sheets

- static/styles/twodsix_basic.css
Bug Fix
Broken contenteditable div fields for Firefox
Fixed contenteditable div fields for Firefox
No
> bugfix(): Fix broken contenteditable div fields for Firefox.

- src/scripts/discord.sh
Previous message should have said:
Autocalculate power used/power max based on the active componts
This version now calculates the entire ship power management section automatically based on the components.
A few things to note:
* Total power for a component is power * total quantity.
* If the name contains "j-Drive" or "m-Drive", power is allocated to those buckets
* The power max is the sum of all power generated (by power components)
* The fields on the power management section fields are no longer changeable by the user
Authored-by: Kampfzwerg with help from marvin9257 and jonepatr
* **What is the current behavior?** (You can also link to an …
> fix: This commit fixes a bug with our discord announcments.

- static/styles/twodsix.css
bug fix
actor tabs are partially obscured
make tabs visible again
Possibly affects prior version.
> fix: FVTT v9 patch 2 style fix

- static/templates/chat/throw-dialog.html
bug fix
difficulties select lists are not working
select lists work
No
> fix: error with if statement

- static/templates/actors/ship-sheet.html
bug fix
Tokenizer module won't work on ship sheet
Tokenizer now works!
No
> fix: allow Tokenizer module to work with ship sheet

- src/module/sheets/TwodsixActorSheet.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-npc-consumable.html
Feature - new, alternative traveller sheet
No sheet exists
Non- default NPC sheet now available as option
No
> feat: Add an NPC sheet

- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/rollItemMacro.ts
- static/lang/en.json
- static/templates/actors/npc-sheet.html
Bug Fix
CE autofire not working for npc sheet nor macros
Firing with auto weapon with CE auto fire rules prompts user for fire mode.
No
> Make npc sheet work for ce autofire rules

- src/module/entities/TwodsixActor.ts
- src/module/handlebars.ts
- src/module/settings/DisplaySettings.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/ship-sheet.html
Feature
Power management section on ship sheet is not useful for some systems
Add an option to show weight management section instead.
No
> feat: add weight management options

- src/module/config.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
feature
No movement field on actor sheet
A field now exists
No
Data template a bit more than required to allow for future expansion
> Add movement rate to traveller sheet

- src/module/handlebars.ts
- src/module/settings/DebugSettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-info.html
- static/templates/actors/parts/actor/actor-notes.html
- static/templates/actors/parts/ship/ship-cargo.html
- static/templates/actors/parts/ship/ship-finance.html
- static/templates/actors/parts/ship/ship-notes.html
feature
only plain content editable fields for larger input blocks
Add option to use TInyMCE for enhanced formatting
No
> feat: add option to use TinyMCE

- src/module/config.ts
- src/module/settings/RulsetSettings.ts
- src/types/twodsix.d.ts
- static/assets/actor/Interface-Overlay-1.svg
- static/lang/en.json
- static/styles/twodsix.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-characteristics-table.html
- static/templates/actors/parts/actor/actor-characteristics.html
- static/templates/chat/throw-dialog.html
- static/templates/items/skills-sheet.html
Feature
User must choose between PSI and Alternative Characteristics
Have an option to select whether PSI and Alternative characteristics are shown.
No
> feat: alternative displays of characteristics

- static/templates/actors/parts/actor/actor-bgi-cd.html
Bug fix
Help text not showing when hovering on certain icons
help text now displays correctly
No
> fix: update pointer help text

- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/items/weapon-sheet.html
Bug fix
Bold font does not display in text areas
Bold font is displayed in a lighter font
No
This is not a real fix for not loading a bold font.  Another PR attempts this but it may break some browsers.
> fix: adjust for missing bold font

- static/styles/twodsix.css
Fix original release not working
N/A
N/A
This is to fix a prior release that didn't work.
> feat: Re-release ship sheet

- static/styles/twodsix.css
Bug Fix
Ship image can extend beyond area
Restrict height to within box
No
> Fix: Update Ship image alignment

- static/styles/twodsix.css
> fix: release ship image adjustment

- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/npc-sheet.html
feature
no traits on npc sheet
add traits to npc sheet
No
> feat: add traits to NPC sheet

- static/templates/actors/parts/actor/actor-items.html
fix
consumables on actor sheet list in order created
consumables listed sorted by name
No
> fix: sort consumables on actor sheet by name

- docs/docs.md
Docs update for Discord invite. Copied link from README
Discord invite invalid
Discord invite valid
No
Thank you for making this module
> update discord invite link

- user_macros/UWP Translator/UPP Translator v0_8.js
Improvements by @TheLaundry
doc update for macros
No default behavior on UWP macro
Adds default behavior and enter
No
> docs: Update UPP Translator v0_8.js

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/npc-sheet.html
feature
Can't see armor on NPC sheet
Armor section added to NPC sheet
No
> feat: add armor section to npc sheet

- static/styles/twodsix.css
fix
Update to fix paragraph styling not released due to not having fix prefix in commit
add prefix
No
> Fix: release #949

- user_macros/Trade Goods Generator/Generate Trade Table v0_8.js
bug fix
quantities not calculated correctly
quantities now show up
No
> doc: fix quantity rolls in trade code generator

- user_macros/Planet Mapper/PlanetIcons v5b.js
bug fix
table header for journal entries runs int starport level
fix
no
> doc: Fix journal entry table header

- src/module/entities/TwodsixActor.ts
- src/module/settings/RulsetSettings.ts
- static/lang/en.json
- static/styles/twodsix.css
Feature
Can't modify token attributes "hits" for traveller (it is calc value)
Can now enter values into the attribute bar input
no
Maybe put damageActor as an actor method?
> feat: make token attributes changable

- static/styles/twodsix.css
bug fix
sheet header icons are fixed so that modules with icons overlap and cause issues
make sheet header icons respect the flex
No
> fix sheet headers

- static/styles/twodsix.css
rerelease of #964
re release
rerelease
No
> fix: try to rerelease

- src/module/handlebars.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/actorDamage.ts
- src/module/utils/createItemMacro.ts
- src/module/utils/sheetUtils.ts
- src/twodsix.ts
- static/styles/twodsix.css
- static/templates/chat/throw-dialog.html
bug fix
margins still active when sheets are minimized
roll dialog not aligning as expected 
ts-ignore issues are annoying
reset margins to zero when minimized
fix roll dialog format
delete/fix a few of the ts-ignore statements
No
> fix: sheet minimization margins and small smaller format errors

- docs/docs.md
> Rerelease Drag and drop items and damage to traveller icons (#961)

- src/module/utils/TwodsixShipActions.ts
bug fix
can't add actor data to position chat rolls
roll data now part of possible roll formula
No
> fix: add missing roll data

- user_macros/Animal Reaction/animalReaction.js
- user_macros/Roll from Table with DM/rollFromTableWithDM.js
- user_macros/Trade Goods Generator/Generate Trade Table for use with Dynamic Macros
docs update
new macros discussed in discord not on GitHub
Add the missing macros
No
> docs: add new macros

- src/module/hooks/dragRulerIntegration.ts
bug fix
OTHER system type defaults to CD style of movement (two stage)
Set default to CE style movement (3 stage)
No
> fix: set OTHER system movement to CE type

- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/items/armor-sheet.html
feature
No way to account for powered armor having zero weight when worn
Add check box to indicate powered armor
fix cases so that only ONE version of the armor has no weight if multiple quantities 
No
> fix: add powered armor

- src/module/handlebars.ts
bug fix
untrained pseudo skill not displayed
fix so untrained shows per system settings
> fix missing untrained

- src/module/handlebars.ts
update - fix bad release of #996 
> fix: Missing Untrained Skill rerelease

- src/module/entities/TwodsixActor.ts
- src/module/sheets/TwodsixShipPositionSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
bug fix
missing actor cause ship position sheet to not be deletable or editable
https://discord.com/channels/739941799820394606/750113408719913021/972416214691373106
Have a check on edit for missing actors
??
> fix: Missing actor with ship positions

- src/module/config.ts
- src/module/entities/TwodsixActor.ts
- src/module/settings.ts
- src/module/settings/RulsetSettings.ts
- src/types/twodsix.d.ts
- static/lang/en.json
feature
No default unarmed attack for actors
Create an unarmed attack for new actors
No
> feat: Add default unarmed attack to new characters

- src/module/config.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/chat/initiative-dialog.html
feature
No way to modify initiative roll
Add optional button to actor skills tab to roll initiative with adjustable DM and type
No
> feat: add initiative roll to actor sheet

- src/module/entities/TwodsixActor.ts
bug fix
characteristic rolls don't function
fix typo so rolls work correctly
no
> fix: bug with characteristic rolls

- static/lang/de.json
Translations update from [Foundry Hub - Weblate](https://weblate.foundryvtt-hub.com) for [Twodsix - Cepheus & Traveller (Unofficial)/main](https://weblate.foundryvtt-hub.com/projects/twodsix/main/).
Current translation status:
> Translations update from Foundry Hub - Weblate

- src/module/sheets/TwodsixActorSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-info.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/ship/ship-components-single.html
bug fix
actor sheets don't behave well when changing font size through FVTT settings
Make scaling behave better
> fix: make actor sheets more robust when changing font size

- src/module/config.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-bgi-animal.html
bug fix of animal types
omnivore select not configured correctly
no siren option
no "other" option
fixed omnivore type
added siren option
added other option and free form text
No
> fix: animal sheet types update

- src/module/hooks/showWoundIcons.ts
- src/module/utils/createItemMacro.ts
bug fix
CE and CEL wound rules don't work correctly when base attribute value is zero
Can't drag and drop item from actor sheet to create macro (race condition with default behavior - make main function sync)
Add more robust logic for cases where an attribute has zero value
Fix drag and drop item onto macro bar 
No
> fix: ce and cel wound logic and macro create from item

- docs/docs.md
Release of prior pr
None
None
No
Updates doc file to use ProseMirror rather than tinymce
> Rerelease PR#1139

- src/module/hooks/dragRulerIntegration.ts
bug fix
Animals don't use Drag Ruler Settings
Animals use same drag ruler settings that Traveller do.
No
> fix: make animals compatible with Drag Ruler

- src/module/entities/TwodsixActor.ts
bug fix
consumables are still attached on drag-drop
consumables are removed on dropping
No
> fix: remove attached consumables during drop

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/showStatusIcons.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixVehicleSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/chat/throw-dialog.html
feature
Not enough detail on roll modifiers or chat messages
Can't modifier all relevant inputs from roll dialog
Add more specifics about roll modifiers
Improve chat flavor
Have all modifiers available on roll dialog
No
> feature: Better roll modifier input and chat message descriptions

- docs/docs.md
wrong release prefix used - re-release of #1171 
> Re-release of PR #1171

- docs/docs.md
re-release of #1174 
N/A
changes from #1174 released
No
> Re-release #1174

- src/module/entities/TwodsixItem.ts
- src/module/settings/RulsetSettings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/templates/chat/throw-dialog.html
optional feature
optional dodge parry rules ignored
rules setting to optionally add dodge and parry
No
> feat: add dodge parry modifier

- src/module/entities/TwodsixActor.ts
- src/module/settings/DisplaySettings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
Feature
Roll chat messages just a simple text line.
Rolling message now can be click-expanded to show detail roll calc modifiers in a table
No
> feature: add expandable roll descriptions

- static/styles/twodsix.css
bug fix
active effects tabs show borders
remove borders
No
> fix: active effects tabs

- src/module/sheets/TwodsixShipSheet.ts
Bug fix
Can't drop component onto empty ship sheet
Allow components to be dropped anywhere on sheet
No
> fix: component drop on ship

- src/module/entities/TwodsixItem.ts
- src/module/sheets/TwodsixSpaceObjectSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
Feature
System can't support Automated Automations
Add chat flags to support automated automation
No
> feat: adding flags for Automated Automation Module

- src/module/entities/TwodsixActor.ts
bug fix
When dropping an item of a different type with same name as another item, system does not add new item
Add new item by checking for type match
No
> fix: duplicate skill and item drops on actor

- src/module/entities/TwodsixActor.ts
Bug fix
Duplicate item drops for components does not match subtype
Check for duplicate includes subtype values
No
> fix: duplicate component drops on ships

- src/module/utils/TwodsixShipActions.ts
bug fix
can't make chat rolls from ship actions
chat rolls can be /r formulas again
no
> fix: roll actions on ships

- src/module/settings.ts
- src/module/sheets/TwodsixAnimalSheet.ts
Bug fixes
Reaction rolls include zeros in chat messages
Auto damage roll is not default
Don't show non-applicable terms
Set auto damage roll setting to default t true
Add Spanish translations 
No
> fix: QOL Issues

- src/module/hooks/autoCompleteIntegration.ts
Add auto complete compatibility
feature
no autocomplete for active effects
support Autocomplete-Inline-Property Module
No
> feat: Create autoCompleteIntegration.ts

- src/module/hooks/autoCompleteIntegration.ts
bug fix
typo, only works for item damage
typo fixed, now works with advanced settings and consumable damage
no
> fix: Update autoCompleteIntegration

- src/module/entities/TwodsixActor.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/utils/sheetUtils.ts
- static/templates/actors/animal-sheet.html
- static/templates/actors/parts/actor/actor-bgi-animal.html
bug fix
error when dropping from compendium
animal sheets don't show skill changes due to AE
fix bug
animal sheets now show skill changes
No
> fix: Active Effects improvements 

- src/module/entities/TwodsixItem.ts
- src/module/sheets/TwodsixAnimalSheet.ts
- src/module/sheets/TwodsixSpaceObjectSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixShipActions.ts
bug fix
rolls do not behave well with dice so nice module settings
rolls respect dice so nice settings
No
> fix: better dice so nice integration

- src/module/entities/TwodsixItem.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/chat/throw-dialog.html
- static/templates/items/weapon-sheet.html
Feature
No modifiers for weapon due to handling characteristics
Add optional weapons handling modifier
No
> feat: add weapons handling modifiers

- src/module/entities/TwodsixItem.ts
- src/module/utils/TwodsixShipActions.ts
- static/lang/en.json
- static/styles/twodsix_moduleFix.css
bug fixes
- can't use weapons handling for Bulky weapons where effect is a formula
- Automated Animations settings display does not work well with Twodsix style
- Skill modifier confusing on item sheets
- Can now use a roll formula in weapons handling effects fields 
- Debug setting for module css corrections now includes AA elements
- Skill modifier renamed to "Roll/Dice Modifier"
* …
> fix: quality of life issues

- src/module/entities/TwodsixItem.ts
bug fix
simplifying strips roll formulas of attributes
Don't simplify
No
> fix: weapons damage formulas

- src/module/hooks/chatCard.ts
- src/module/hooks/ready.ts
bug fix
chain rolls still roll when cancelled
respect abort/cancel
No
> fix: respect aborting roll

- src/module/hooks/chatCard.ts
- static/lang/en.json
Bug fix
Typo in chain roll DM
Fix chain roll DM function
Comment out unused chatCard code
No
> fix: clean-up chatCard code

- src/module/sheets/TwodsixActorSheet.ts
- src/twodsix.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-info.html
- static/templates/actors/ship-sheet.html
feature
No way to record XP information for Traveller
Add section on info tab to record information
No
> feat: add xp information to actor

- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/sheets/TwodsixSpaceObjectSheet.ts
- src/module/sheets/TwodsixVehicleSheet.ts
- src/module/utils/TwodsixShipActions.ts
- src/module/utils/sheetUtils.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/space-object-sheet.html
features
Need more data fields on space object sheet
Add additional fields
Maybe document references get nuked
> feat: add data fields to space-object

- src/module/sheets/TwodsixActorSheet.ts
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
bug fix
ammo buttons not working
fixed buttons
no
> fix: ammo buttons not working

- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/templates/items/parts/component-sheet-tabbed.html
- static/templates/items/parts/weapon-sheet-tabbed.html
Monk's journal style clashes makes it unusable
fix poor English
Remove clashes with tabbed item sheets
chain roll has poor grammar 
fix problem
no
> fix: style clash with Monks Journal

- src/module/entities/TwodsixActor.ts
bug fix
duplicating actors does not preserve token settings
don't override token settings when duplicating
refactor onCreate actor to have fewer updates
> fix: creating and duplicating actors

- src/module/config.ts
- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/settings.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-npc-consumable.html
- static/templates/actors/parts/ship/ship-cargo.html
- static/templates/actors/parts/ship/ship-state-grid.html
- static/templates/actors/ship-sheet.html
- static/templates/items/computer-sheet.html
- static/templates/items/consumable-sheet.html
- static/templates/items/parts/common-parts.html
- static/templates/items/parts/component-sheet-flat.html
- static/templates/items/parts/component-sheet-tabbed.html
- static/templates/items/parts/weapon-sheet-tabbed.html
features and fixes
No way to track bandwidth and processing power
add computers as item type
add software as consumable type
add processing power and bandwidth fields to computer and software components.
add optional bandwidth fields to ship actor and sheet
add setting to show bandwidth on sheet
add calcs to determine bandwidth available and used
fix cleanup functions when Untrained is turned on and off
fix active effect display on actor sheet when editing
Add edit and delete icons to npc actor sheet for items …
> feat: computers and software and other improvements

- package-lock.json
- src/module/handlebars.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/types/template.d.ts
- static/lang/en.json
- static/template.json
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/items/consumable-sheet.html
Feature
Software attachments to computer items can't be toggled on /off
No summary of processing Power for computer
Software attachments can be toggled on/off
Summary of processing power used/avail listed in short description area
No
Software must be an attachment to work.
> feat: Computer attachment changes

- src/module/entities/TwodsixActor.ts
- src/module/hooks/itemPilesIntegration.ts
- static/lang/en.json
Bug fixes
Not Item or Actor type localization strings
Item piles not happy with _updateDerivedData function
Add localization
Add check for item Piles
Add improved item filters for Item Piles
No
> fix: Add item type labels

- src/module/entities/TwodsixItem.ts
bug fix
software attachment DM active when software is off
software DM only include when software is on.
No
> fix: Software DM applying when Software is inactive

- src/module/hooks/showStatusIcons.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
features
- Can't edit /view consumable directly from parent item
- unclear where consumables / attachments are placed
- Edit button added to each attached consumable
- Consumables and Attachments list parent item
No
> fix: Consumables qol issues

- src/module/sheets/TwodsixShipPositionSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
The new robots are now allowed to fill a ship position(automated duties)
robots throw some unreadable error
> fix: allow robot actors in the ship positions.

- src/module/hooks/addGMControlButtons.ts
bug fix
Having default ownership of token/actor is not considered.
Check for default ownership without an explicit ownership setting.  Randomly select owner if still more than one owner.
No
> fix: Consider Default Ownership in Request Roll Function

- static/lang/en.json
- static/lang/es.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-items.html
Bug fixes
- spacing not correct on weapons listing when localized
- equipped state not localized
- fix spacing
- add localization
No
> fix: More format fixes

- src/module/hooks/showStatusIcons.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
bug fix
* issue with deleting encumbered effects and items
* delete should work correctly
No
> fix: odd TS cast of <string> causing errors

- src/module/hooks/chatCard.ts
- src/module/hooks/dragRulerIntegration.ts
- src/module/hooks/showStatusIcons.ts
bug fix
some settings don't work for CDEE
fix missing switch cases
No
> fix: missing settings for CDEE

- package-lock.json
- package.json
Reverts xdy/twodsix-foundryvtt#1404
> Revert "chore(deps-dev): bump @rollup/plugin-commonjs from 24.1.0 to 25.0.3"

- package-lock.json
- package.json
Reverts xdy/twodsix-foundryvtt#1406
> Revert "chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.62.0 to 6.1.0"

- src/module/config.ts
- src/module/hooks/renderChatMessage.ts
- src/module/settings/RulsetSettings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
feature
no degrees of success note on rolls
add degrees of success for non-attack rolls
No
> feat: add degrees of success

- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/sheetUtils.ts
- static/lang/en.json
- static/templates/actors/space-object-sheet.html
bug fix
Can't delete pdf reference from item
Can't add pdf reference to space-object
fix above bugs
No
> fix: Fix pdf references for items

- src/migrations/2023_08_30_12_58_add_associatedSkill_to_spells.ts
- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/template.json
- static/templates/actors/parts/actor/actor-info.html
- static/templates/items/spell-sheet.html
feature
Spells don't have linked skills or damage fields
Monk's Enhanced Journal format is not compatible with default format
Add associated skill name field
Add damage field
Migrate default sorcery skill name to associated if blank
Monk's Enhanced Journal now works better with default format
No
> feat: initial changes to add associatedSkills to spells

- src/module/entities/TwodsixActor.ts
- src/module/hooks/showStatusIcons.ts
- src/module/sheets/TwodsixShipSheet.ts
- static/templates/actors/parts/ship/ship-components-double.html
bug fixes
- ship component listing headers overlap items
- ship positions added twice on drag-drop onto add position box
- drag drop of item on non-traveller triggers encumbrance check
-fix above issues
> fix: Ship sheet bugs

- src/module/sheets/AbstractTwodsixActorSheet.ts
bug fix
robots and animals don't have prompt asking for auto fire mode
allow these actors to trigger prompt
No
> fix: use resolve unknown auto mode for robots and animals

- src/module/entities/TwodsixActor.ts
fix / refactor
can't call ship action from outside
add ship method to execute an action
No
> fix: make a doShipAction method to work with TAH

- src/module/config.ts
- src/module/hooks/diceTrayIntegration.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixAnimalSheet.ts
- src/module/sheets/TwodsixRobotSheet.ts
- src/module/utils/TwodsixRollSettings.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-characteristics-rotate.html
- static/templates/actors/parts/actor/actor-characteristics-table.html
- static/templates/actors/parts/actor/actor-characteristics.html
feature
layout of characteristics on Traveler sheet not pleasing
add additional mode to omit PSI
refactor characteristics display to use #each
Make characteristics use a flex wrap
> feat: improve characteristic displays on Traveller Sheet

- src/module/entities/TwodsixActor.ts
- src/module/hooks/addGMControlButtons.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/AbstractTwodsixItemSheet.ts
- src/module/utils/utils.ts
feature
Skills list for GM roll request is unsorted
Sort list alphabetically
No
> feat: sort skills list for GM Roll Request

- src/module/hooks/chatCard.ts
feature
Chat messages can't use @SkillRoll link
Add ability to use @SkillRoll from chat.
No
> feat: add @SkillRoll to chat cards

- src/module/hooks/itemPilesIntegration.ts
- static/styles/twodsix.css
- static/templates/actors/parts/actor/actor-characteristics-rotate.html
- static/templates/misc/advanced-settings.html
- static/templates/misc/setting-partial.html
bug fixes
- ItemPiles integration references system.finances.cash
- style errors for rotated characteristic display
- ItemPiles integration references system.financeValues.cash
- improve styling for rotated characteristic display
No
> fix: Misc fixes

- src/module/hooks/ready.ts
Fix of broken release for v4.12
> feat:  add Target DM roll setting

- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/enrichers.ts
feature
Difficulty for SkillRolls must be even integers 
Allow odd values
No
> fix: allow odd difficulties for SkillRoll

- src/module/settings/DisplaySettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/template.json
- static/templates/actors/parts/actor/actor-skill-item.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/items/skills-sheet.html
feature
No way to organize skills into group
Skills can be organized by group labels
No
> feat: add skill headers

- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/actor/actor-skills.html
feature
Skill Group Headers Static
Skill Group Headers Toggle Display
No
> feat: allow skill headers to be toggled

- src/migrations/2024_01_08_17_12_refactor_range.ts
- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixCombatant.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/renderItemSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/utils/migration-utils.ts
- src/types/template.d.ts
bug fix
weapon.system.range not migrated from number to string
migrate to string
> fix: missing migration for weapon range

- src/module/entities/TwodsixActor.ts
Bug fix
Can't drop traits on animals/actors
Allow traits to be dropped (fix case where associatedSkillName doesn't exist on item)
No
> fix: empty string is  Undefined skill

- static/lang/de.json
- static/lang/en.json
- static/lang/es.json
- static/lang/fr.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_de_changes.css
- static/styles/twodsix_fr_changes.css
- static/styles/twodsix_sv_changes.css
- static/templates/actors/parts/actor/actor-skills.html
style fix
add skill button/graphic too large
Make simpler with + graphic
No
> fix: improve add skill graphic

- src/module/sheets/TwodsixItemSheet.ts
bug fix
cannot open ship items
now ship items can be opened
no
> fix: unable to open ship items

- src/module/hooks/diceTrayIntegration.ts
bug fix
dice tray integration no longer works
update dice tray integration hook for new API
no
> fix: update dice-tray integration

- src/module/sheets/TwodsixItemSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
- static/templates/items/parts/consumables-part.html
- static/templates/items/parts/weapon-parts/weapon-magazine.html
bug fixes
Issue when changing item to consumable.  System still allows attachments.
CSS issues with pull-downs and AA
ammo field is text input should be number
fixes.
> fix: Fix attachments on consumables

- src/module/data/characters.ts
- src/module/data/item-base.ts
- src/module/data/item.ts
- static/templates/items/parts/weapon-parts/weapon-magazine.html
Bug fix
Migrations fire without checking for field in source
Migrations now check
> fix: bad migrations

- static/lang/en.json
bug fix
typo in setting description
fix typo
No
> fix: typo in settings description

- src/module/utils/enrichers.ts
bug fix
Table rolls show d20
Table rolls show 2d6
no
> chore: Update enrichers to show 2d6

- src/module/hooks/renderActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/enrichers.ts
- static/templates/actors/parts/actor/actor-attachment-consumable-list.html
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-skills.html
Bug Fix
Skill headers close on edit
Keep skill headers open
Revert to old style - don't use details
> fix: skill header toggle bug

- src/module/entities/TwodsixActiveEffect.ts
bug fix
AE changes through macros don't trigger status condition changes
AE changes trigger encumbrance checks
?
> fix: AE through macros can trigger encumbrance check

- README.md
bug fix
no % translated badge for RU
add badge for RU
No
> chore: add RU badge

- static/lang/en.json
- static/templates/actors/battle-sheet.html
bug fix
error when trying to create a new position on battle sheet
Can now create new ship position on battle sheet
No
> fix: add new ship position from battle sheet

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/battle-sheet.html
bug fix
battle sheet not responsive enough to smaller widths
use @container options to change column settings
No
> fix: more responsive battle sheet

- static/templates/actors/parts/actor/actor-info.html
bug fix
Spacing between dice symbol and sonic ability level too small
Add extra space between items
No
> fix: add space

- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
- static/system.json
- static/templates/actors/parts/ship/ship-component-double-item.hbs
bug fix
Trying to add ship components in the default double line display causes errors
Style issues with v13
Fix missing quotation mark from double line display handlebar
Misc CSS fixes
NO
> fix: adding ship components not working

- static/styles/twodsix.css
- static/templates/misc/advanced-settings.hbs
bug fix
can't see scrollbar on settings windows
make division scrollable and correct margin
No
> fix: scroll not visible on settings windows

- src/module/sheets/AbstractTwodsixActorSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
bug fix
JOAT value on traveller & NPC sheets doesn't change on update
Vehicle notes box height too small if using content editable
JOAT now updates correctly
Height added to input box and scroll added
> fix:  joat value not changing

- src/module/entities/TwodsixActor.ts
Bug fix
Importing compendium item folder to actor doesn't transfer all data
Importing folder from item compendium now works.
No
> fix: importing folder from compendium need to get item

- .github/workflows/test-release.yml
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_de_changes.css
- static/styles/twodsix_sv_changes.css
- static/templates/actors/parts/actor/actor-core-buttons.hbs
- static/templates/actors/parts/actor/actor-items.hbs
feature
can't easily send inventory item descriptions to chat
added action button to send to chat
No
> feat: add chat buttons to items

- .gitignore
- static/styles/twodsix.css
bug fix
No cell borders for Journal entry tables
Add cell borders for JE Tables in both display and prose mirror
No
> fix: add prosemirror cell borders for tables

- static/templates/actors/parts/actor/actor-items.hbs
bug fix
Can't change location of a consumable from actor sheet and localization broken
Localization fixed and can now change location
No
> fix: Consumables can't change location state on actor sheet
