xdy/twodsix-foundryvtt

- package-lock.json
- src/module/sheets/TwodsixActorSheet.ts
- static/system.json
Bug issue #67 has been fixed, big thank you to Daddi.
Skill list and item list no longer jumps back to top on changes.
> Fix: Issue #67, Skills and items no longer jump

- src/module/hooks/createItem.ts
- src/module/hooks/renderItemSheet.ts
- static/lang/en.json
- static/lang/sv.json
- webpack.config.ts
feature
Fixes #105 
Currently adding new items requires several steps. As it sometimes is
desirable to add several items at once this can become tedious.
Adds a button to automatically close the current newly added item and creates a new one.
No
> new feature: close and create new item in one go fix: close and create new item in one go 

- src/module/config.ts
- src/module/hooks/renderSettingsConfig.ts
- src/module/settings.ts
- static/lang/en.json
- static/lang/sv.json
- webpack.config.ts
feature
Previously the users needed to reference the documentation in order to set the correct values for a given rulset.
This change adds a dropdown containing supported rulesets and populates the corresponding settings
fields.
No
* Part of #183
>  fix: add dropdown with settings for rulesets

- src/module/config.ts
- src/module/hooks/renderChatMessage.ts
- src/module/utils/TwodsixRolls.ts
- static/styles/twodsix.css
feature
Previously no coloring was shown for critical successes/fails.
This change calculates if a roll was a crit and displays it accordingly in the chat message using a red/green color.
no
Fix #120,  part of #168
> fix: added coloring of crit success/fail

- docs/docs.md
- src/module/handlebars.ts
- src/module/settings.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/lang/en.json
- static/lang/sv.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
feature
Previously the default behavior was to directly roll a skill without modifiers.
This change makes the roll dialog come up as default when clicking on the skill. Shift clicking now does an automatic roll. 
A settings option has been added to revert to the previous behavior for those who prefer that.
Fix #267
> fix: switch behavior of skill roll in character sheet

- src/module/sheets/TwodsixItemSheet.ts
feature
Currently the item windows are smaller than the content and requires scrolling.
This change makes it so that the window size adapts to the content.
No
Fix #264
I'm not entirely sure if this has any repercussions elsewhere, so please let me know if it has. I've tried opening a bunch of various windows and it all looks good.
The character/ship windows also …
> fix: change so that item window size adapts to content

- package-lock.json
- src/module/config.ts
- src/module/utils/TwodsixRolls.ts
- static/styles/twodsix.css
- static/template.json
- static/templates/items/skills-sheet.html
- [ x] We use semantic versioning (https://github.com/semantic-release/semantic-release to be specific), so follow https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines *EXCEPT*, don't use 'feat:' if you're not me. Stepping major versions until 1.0 is a deliberate decision (after that, it'll be full semantic versioning.) 
Adds the ability to set default rolltype for a skill. (Needed for traits, so might as well make it available in the gui).
Rolltype can only be set temporarily.
* **What is the new behavior (if this is a feature …
> Skill rolltype default

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/createItem.ts
- src/module/hooks/renderItemSheet.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- static/template.json
- static/templates/items/parts/common-parts.html
Big change to how rolling is performed. Backward compatible, and using
both methods for now. Not meant to be merged.
hopefully not much :) I removed the dropdown to select characteristics when rolling for a single characteristics. Other than that behavior should be the same
No
* Fix #212
> WIP fix: change rolling

- static/template.json
bug fix/feature
currently the default is 0 for both max and value for hits
Since the str/dex/end are 21 in total the default  hits number should reflect that.
No
I  was considering  a migration to change all hit max/value to be 21 but then I thought that it might interfere with if someone manually has set the values of the hits to 0. Definitely can add that if we …
> fix: change default value of hits

- static/templates/actors/parts/actor/actor-items.html
bug  fix
It rolls damage twice for burst attacks
It only rolls once
No
Did a bit of cleanup there too
> fix: burst attack now only rolls damage once

- src/module/entities/TwodsixActor.ts
- src/module/hooks/addUntrainedSkill.ts
- src/module/hooks/index.ts
- src/twodsix.ts
Bug fix
Previously creating a new TwodsixActor did create an untrained skill, however creating an Actor does not create an untrained skill. 
This fix makes it so that an untrained skill is created in both cases.
No
Fix #328
> fix: change so that Actor creates untrained skill

- src/module/hooks/renderChatMessage.ts
- src/module/utils/TwodsixDiceRoll.ts
bug fix
Currently private dice rolls show the effect to everyone instead of obfuscating it. There was also a bug ignoring the user's choice of roll mode in the roll dialog
This change hides the effect and does not colorize the result if the user is not allowed to view it. It also fixes the issue with roll mode.
No
Fix #321
> WIP: fix: change renderChatMessage hook to obfuscate hidden rolls properly

- src/twodsix.ts
- static/templates/actors/actor-sheet.html
- static/templates/actors/parts/actor/actor-characteristics.html
- static/templates/actors/ship-sheet.html
feature
Previously character/ship sheets could only show the full information.
This change allows for showing limited information for characters/ships.
No
Fix #334
> WIP: fix: character sheet can show limited info

- src/module/config.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/deleteItem.ts
- src/module/hooks/updateItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/utils/sheetUtils.ts
- src/twodsix.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/items/armor-sheet.html
- static/templates/items/augment-sheet.html
- static/templates/items/consumable-sheet.html
- static/templates/items/dialogs/create-consumable.html
- static/templates/items/equipment-sheet.html
- static/templates/items/item-sheet.html
- static/templates/items/junk-sheet.html
- static/templates/items/parts/common-parts.html
- static/templates/items/parts/consumables-part.html
- static/templates/items/storage-sheet.html
- static/templates/items/tool-sheet.html
- static/templates/items/weapon-sheet.html
- webpack.config.ts
Note, this PR is against the development branch so that it can be tested!
feature
There are no consumables so ammo has to be handled manually
It adds an item called consumables and let's one attach those to other items (not skills though). An item can have any number of consumables, and for weapons one can set one of the attached consumables as being consumed when attacking. Consumables have their own section in the items list of the character sheet and show up under the attached item for increasing/decreasing …
> WIP: fix: add consumables

- user_macros/NPC Parsers/Parser for CE 1001 Characters.js
Fix for skills lookup to only look at type=='skills'
> Update Parser for CE 1001 Characters.js

- user_macros/NPC Parsers/Parser for CL Character Generator v2.js
Fix skill lookup to only search type==='skills'
> Update Parser for CL Character Generator v2.js

- package.json
- src/migrations/2021_02_10_10_10-old_migrations.ts
- src/migrations/2021_02_10_10_20-ship_stats.ts
- src/module/hooks/ready.ts
- src/module/migration.ts
- src/scripts/create_migration.ts
- static/template.json
- static/templates/actors/parts/ship/ship-cargo.html
- static/templates/actors/parts/ship/ship-crew.html
- static/templates/actors/parts/ship/ship-notes.html
- static/templates/actors/ship-sheet.html
bug fix
Previously token bars were broken for ships.
This commit fixes a bug where all ship properties were incorrectly stored under a "ship" property and changes the format of hull, power, and fuel to be compatible with the token bars.
There's a migration that might need manual interference. However the user receives a dialog so they have some control themselves …
> fix: make ship hull avaialble as token bar

- package-lock.json
- static/styles/twodsix.css
- static/templates/actors/actor-sheet.html
> If someone figures out how to move the armor to the bottom of that field (with the image constrained to not overflow the armor fields) it could finally be moved out of 'buggy features'. It's fairly useful as is (though, obviously, setting armor from worn equipment would be better).
https://discord.com/channels/739941799820394606/750113408719913021/825739199897665586
- Fields only appeared if art was not too long
- And, if experimental features were enabled
- Fields float above the art if it's too long
- Works without needing to enable experimental features
> fix(actor sheet): make armor fields sit on top of character art, remove from experimental flag

- static/styles/twodsix.css
Removes our custom `.hidden` class that conflicts with base Foundry usage
Hiding an actor in the Combat Tracker would make the actor completely hidden in the list
Hiding an actor will default to the base behavior of Foundry (currently making the actor opaque to the GM)
I do not think so. I could find no usages of this class in the markup or scripts, so I just opted to remove the entire class itself.
Fixes xdy/twodsix-foundryvtt#473
> fix(Combat Tracker): hiding actor makes it opaque instead of completely hidden

- src/module/utils/TwodsixDiceRoll.ts
This fixes the calculation of the effect when critical are rolled
- [ X] Docs have been added / updated (for bug fixes / features)
This is a bug fix for critical rolls
Addresses
https://github.com/xdy/twodsix-foundryvtt/issues/471
I have not been able to validate the change works!
> Update TwodsixDiceRoll.ts to Fix Effect Calculation for Critical

- src/module/utils/rollItemMacro.ts
- static/lang/en.json
- Now rolls damage as expected
- Dialog text moved to localization file
- only english translation provided in the PR
- If using CEL rate of fire rules, use hotbar macro prompts for attack type
- I don't use or currently understand how the CE ROF rules work, so I didn't attempt to implement a dialog for that. It should not be too difficult for someone else to add, though.
Fixes #472
Thanks to @marvin9257 for the initial code to get this started.
> fix: Fix and enhance weapon hotbar macro

- user_macros/UWP Translator/UWP Translator.js
File was missing some lines
fix of the old version of the UWP translator macro - some of the trade code function was cut out.
Missing many trade codes
Now does the full CL trade codes - restores full function
No
> Fix: old UWP translator had truncated the trade codes

- src/module/entities/TwodsixItem.ts
Changing roll formula so that @attr are calculated correctly.
This fixes a bug where attributes in damage roll formulas are not calculated correctly.  For example, an unarmed attack in CL should have the damage formula: max(@characteristics.strength.mod, 1).  However, the strength mod was always 0 because there was no actor reference.
Attributes in damage rolls are not included correctly.
Should work now.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
> fix: damage formulas do not calculate attributes correctly

- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
This commit tries to fix several errors with consumables:
1) not being able to delete phantom consumables
2)  deleting from actor sheet did not delete from item
Bug fixes to address multiple problems with consumable deleting.
Run errors and phantom consumables that can't be deleted. Tries to address item number #490 
Able to delete phantom consumables and better checking for unlinked consumables when deleting.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
> fix: consumable bugs

- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
This fixes two bugs introduced in last update related to item drops.
1) Tools items could not be dropped onto character sheet because they did not have attached consumables.
2) The default icon overwrote and custom icon on weapon drop
1) Tools now can be dropped onto sheet and code checks to see whether data.consumables exists first.
2) Weapons drops now respect a custom icon
None
No
* …
> Fix item drop

- user_macros/Trade Goods Generator/Generate Trade Table v0_8.js
- user_macros/Trade Goods Generator/Generate Trade Table v6.js
- user_macros/UWP Translator/UPP Translator v0_8.js
- user_macros/UWP Translator/UWP Translator.js
Convert text values to numbers
This is a bug fix: trade codes were not generated completely due to tex/number conversion problem
Trade codes incomplete
Trade codes now generated correctly
No
> fix: Fix trade codes error

- user_macros/Update Initiative/UpdateInitiative v0_8.js
Data for game.combats.active not stable.  Use game.combat instead.  Fix per @ForjaSalvaje.
Fix for initiative macro.  Data for game.combats.active not reliable.
Initiative macro does not work.
Reliably adds tactics skill to macro roll.
No
> Fix:  for game.combats.active

- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- static/template.json
Error caused by item not having a consumables array - check for existence first.
Bug fix...when trying to delete consumables, the check for attached consumables always assumed that the consumables array existed.  Now code checks that it exists. Bug found by Tremandur.
Can't delete a consumable from consumables tab.
Consumables can be deleted.
No
> fix: Inability to delete consumable

- src/module/entities/TwodsixActor.ts
- src/module/settings.ts
- static/lang/en.json
This change allows syncing of actor image and token icon the first time the actor image is changed (as is the standard FVTT behavior).
Adds a Twodsix system setting so that users can choose to use FVTT default icon for prototype tokens rather than the Twodsix specific icons.  This allows the token icon to be automatically updated when selecting a new actor image.
Prototype tokens are set to Twodsix specific icons.  Changing the actor image also requires one to change the token image as a separate step - rather than the expected behavior of both changing on first update. …
> fix: add setting to set new actor prototype icons to FVTT system default

- src/module/entities/TwodsixActor.ts
- src/module/hooks/updateHits.ts
- src/module/utils/actorDamage.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/actor-sheet.html
- static/templates/actors/damage-dialog.html
Adapt code and character sheet to allow damage to work with lifeblood and stamina stats rather than other characteristics
add: ability to use damage code with lifeblood and stamina
fix: when using strength for lifeblood, damage and damage dialogs now display consistently.
feature change
bug fix
fields are manual
current damage dialog does not adapt to changes in characteristics.
damage object works as with regular stats
* **Does this PR introduce a breaking change?** (What changes might users need to make in …
> Allow damage actor code to work with lifeblood and stamina

- docs/docs.md
This changes the description for Cepheus Deluxe to include recent changes for LFB and STA with respect to damage.
Document changes to better describe LFB and STA damage changes for CD.
No information is available
Description of the option to show STA and LFB in the biography section and how it overrides existing damage mechanism of characteristics.
No
> Update Cepheus Deluxe description to ver 0.8.26

- src/module/entities/TwodsixActor.ts
- static/templates/actors/parts/actor/actor-skills.html
Moves the JOAT skill value inside the skills list/
JOAT value is outside, on top of the list.  This location can be confusing.
JOAT skill is first item in list.
No.
fixes another issue where "Untrained skill" defaults to "STR" modifier.
> fix: Move JOAT line to inside skills list

- src/module/sheets/TwodsixActorSheet.ts
- static/styles/twodsix.css
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-skills.html
Adds the ability to edit consumable quantities directly on actor sheet.
Must click the edit button to edit value
Edit right on the actor sheet.
No
> add: allow consumable quantities to be edited

- src/module/handlebars.ts
- src/module/settings.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/templates/actors/parts/ship/ship-components-double.html
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/actors/parts/ship/ship-storage.html
- static/templates/actors/ship-sheet.html
- static/templates/items/component-sheet.html
Adds a feature to show ship component list on single line.  It required some refactor of the tab sheet html to make the code understandable and not too repetitive.  Also, expands real estate on ship tabs.  Adds overlooked localization to storage tab item type.
Must use double column format. Tabs too narrow.  Item types not localized.  Oh my.
Option to choose between single or double column format.  Tabs wider. Better localization.
* **Does this PR introduce a breaking change?** (What changes might users need …
> add: add option to show ship component on single line

- src/module/settings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/lang/de.json
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
- static/templates/actors/parts/actor/actor-items.html
* New Feature: ability to auto calculate the current armor/encumbrance values based on the inventory
* Encumbrance not viewable at all
* Values for encumbrance/armor are not auto calculated
* see above
* New value in the Character overview
* New switches for the items in the character inventory to determine if the item is in the 'Backpack', Equiped or on the ship(not with the Traveller …
> Add encumberance

- static/styles/twodsix.css
- static/templates/actors/parts/ship/ship-components-double.html
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/actors/parts/ship/ship-storage.html
Style change for ship sheet.  Headers for stored items scroll off the screen.  Fix them to always be on top.
Headers scroll off the screen making tables difficult to read.
Headers are fixed.
No
> fix: component and storage headers so they don't scroll

- static/lang/en.json
- static/styles/twodsix.css
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
Shortens title, makes calc value unedited, changes icon for encumbrance.  Fixes some minor styling issues for rest of big area.
Long title, reused icon, calculated field can selected and edited.
Fixes these
No
> Shorten encumbrance title and change its icon; restyle a bit

- src/module/utils/TwodsixRollSettings.ts
This is a larger issue as we have both item.data.name and item.data.data.name.  The two aren't identical.
Bug fix: For item rolls (like an attack) the item named referenced is item.data.data.name rather than item.data.name.  The name entered on the Item sheet is actually item.data.name.
Depending on how item was created, name will be incorrect or missing in dialog.
Fix dialog.
No
* …
> Fix: incorrect reference to item root name.

- static/styles/twodsix.css
- static/templates/actors/parts/ship/ship-components-double.html
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/actors/parts/ship/ship-storage.html
- static/templates/actors/ship-sheet.html
- static/templates/items/weapon-sheet.html
-- Refactors the style sheet to use css variables for colors rather than static values.  This should make future updates of format easier.
-- Fixes actor image on ship sheet
-- Fixes certain input fields on weapon sheet to not use content editable
-- Ship item lists difficult to read
-- No armor field on ship sheet
-- identical colors are references multiple times by value
-- ship actor image does not preserve aspect ratio
-- Certain fields on weapon sheet do not have default styling
-- No shading for alternate lines on ship item lists
-- No armor field on ship sheet
* …
> fix: use var for colors rather than static values and fix style issues

- static/templates/items/weapon-sheet.html
Bug fix for weapons fire rate
Can only enter single value
Can enter any "text format
No
> fix: weapon input field can't be forced to a single number

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
Traveller image overlaps other areas.  Make it fit into image box.
Bug fix:  fix traveller actor image alignment to fit within box
Traveller image does not correctly fill the image box or extends past/
Constrain image to box and make it centered while preserving aspect ratio.
No
> fix: traveller image format

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
Bug Fix: Long consumable names overlap item box (does not expand correctly)
Overlap of box boundaries
Make it auto sizable
No
> fix: vertical alignment of consumables row

- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
Bug fix: armor, encumbrance and rads should be numbers and not text 
Values typed to strings rather than numbers - cause issues when using values as resource
Values a kept as numbers - per template
No
> fix: encumbrance, armor and rads should be numbers and not text

- static/templates/actors/parts/actor/actor-characteristics.html
Bug Fix: Short alternative names don't align the values 
Value, mod, and damage not aligned in boxes if shortName is too short
Force a line break regardless of length
No
> fix: adjust for short alternative names

- src/module/utils/sheetUtils.ts
Javascript comparison not working with mixed strings and numbers
bug fix: getKeyByValue function was not working if using a mixed string number comparison.  Fix courtesy of @jonepatr 
Can not call a characteristic roll and have the difficulty displayed correctly in chat
Difficulty selected displays correctly.
No
> fix: getKeyByValue

- static/styles/twodsix.css
bug fix
Background image does not fill active display area
Background image now fills area, but is allowed to repeat.  Cover is not working to autofill.
No
> fix: background image not displaying correctly

- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/createItemMacro.ts
- src/module/utils/rollItemMacro.ts
Fix - users want to be able to make skill rolls without having to create and control an actor (for the GM).
Unable to make skill rolls (using a macro) without an attached actor that is controlled
Can create macro skill roll that works without an actor.  Create an skill (item), drag and drop item to macro bar - run macro results in dialog for a standard skill roll. _Does not work for a weapon._
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
> fix: allow unattached skill rolls

- src/module/utils/createItemMacro.ts
bug fix
createItemMacro include an "entity" reference.  No longer valid in FVTTv9
Change to simple game.macros.getName() reference
No
> fix: remove entity reference in createItemMacro

- src/module/AdvancedSettings.ts
- src/module/hooks/renderSettingsConfig.ts
- src/module/settings.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/misc/advanced-settings.html
feature
Previously all settings were placed on one settings page.
This change allows for creating sub pages for settings.
No
Fix #183
> feature: Sub menus for settings

- src/module/entities/TwodsixCombatant.ts
- src/module/hooks/ready.ts
- src/module/settings/RulsetSettings.ts
- src/twodsix.ts
feature
Previously there was only an initiative formula for travellers.
This update allows for defining two independent initiative for
those actors.
Fix #380
> feat: use two separate initiative formulas for ships and travellers

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/templates/items/skills-sheet.html
feature
Previously one could not use skills in roll formulas.
This change allows for using skills in roll formulas.
Spaces are remove from skill names, thus Gun Combat becomes GunCombat.
Normally the setting for untrained skill value is returned when an actor
lacks the skill. Adding an undnerscore (_) at the end of the name will make the
skill default to 0 if it doesn't exist or for a negative value.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due …
> feat: allow for skill in roll formulas

- src/module/config.ts
bug fix
previously the cepheus deluxe initiative was 2d6.
This change sets it to 2d6 + @skills.Tactics_ + @characteristics.intelligence.mod
No
> fix: use correct cepheus deluxe initiative formula

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/items/skills-sheet.html
Fix spacing issues on skill item sheet
Bug fix
Spacing of fields on skill sheet inconsistent
Make spacing of fields uniform
No
> fix: clean-up skill sheet

- src/module/utils/createItemMacro.ts
Current code forces it to be a rollItemMacro
Bug fix
When macros are dropped onto macro bar, they are recast to rollItemMacros (scripts)
If item is already a macro, leave it as a macro
No
> fix: drag and drop macro onto macro bar

- .releaserc.yml
- src/scripts/release.sh
No
Changes the manifest to always point to the tagged release rather than the latest one.
All releases actually point to latest.
It should be possible to install old versions.
Hopefully not...
n/a
> Change to always use the tag rather than latest

- src/module/sheets/AbstractTwodsixActorSheet.ts
bug fix
all armor in inventory counts towards equipped value
only armor being worn
No
IMPORTANT - the linter / type check shows an error.  It thinks the variable item.data.data.equipped is binary where it is actually a string.
> fix: calculate armor correctly

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
add namespace prefix
Bug fix
CSS variables can be easily overwritten by other modules
add a namespace prefix of s2d6- to all css variables in style sheet
No
> fix: protect Twodsix style variables

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/ship/ship-components-double.html
- static/templates/actors/parts/ship/ship-components-single.html
format change
Ship component icons re shown for each item
Only show icons for header rows
No
> fix: eliminate component icons from rows

- src/module/settings.ts
- src/module/settings/DebugSettings.ts
- src/module/settings/DisplaySettings.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix_moduleFix.css
feature
Certain modules don't work well with the default Twodsix style
Add an optional style sheet to correct identified issues:
- Item icons not respecting aspect ratio for item sheets
- Dice Tray input box shifted out of line
- GM Screen tabs don't have dar background
- PopOut! resizing Ship actor sheet
- Allow side bar poppets to be resized
- Macro code can't be seen due to Advanced Macro light background for editor
* **Does this PR introduce a breaking change?** (What changes might users need to make in …
> feature: add optional stylesheet

- static/styles/twodsix_moduleFix.css
Bug Fix
Advanced Macros not behaving well with Twodsix default style
Force text and background to Twodsix default.  However, loose Advanced Macro context colors.
No
> fix: Advanced Macros Not working

- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/ship-sheet.html
feature
No way to link a ship deck plan scene and ship actor
Drag and drop a scene to hyperlink scene.  Clicking link opens the scene in view mode.
No
> feat: add a deck plan hyperlink for ship

- src/module/handlebars.ts
- src/module/utils/rollItemMacro.ts
- user_macros/Planet Mapper/CepheusDeluxeGalaxyImporter.js
- user_macros/Planet Mapper/PlanetIcons v5b.js
show skill roll depending on "invertSkillRollShiftClick" setting.
bug fix
Skill roll macros do not show dialog to select difficulty, characteristic, etc.
FVTT does not like having zero padding
Skill roll macros now show dialog if  "invertSkillRollShiftClick" is false.
Non-zero padding added to mapping macros
No
> fix: show skill roll dialog for macros

- static/styles/twodsix_moduleFix.css
Bug Fix
The Tidy UI module causes the tabs on the system settings to grow too large
Tabs don't grow when using the debug-correct some css issues setting
No
> fix: Tidy UI Module tab issue

- src/module/handlebars.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/chat/throw-dialog.html
- static/templates/items/skills-sheet.html
feature - add difficulty numbers / values after text label on skill rolls
Only text appears
text and value also appear.
No
> feat: show difficulty values along with text

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/actorDamage.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/template.json
- static/templates/actors/damage-dialog.html
- static/templates/items/consumable-sheet.html
- static/templates/items/weapon-sheet.html
feature
No allowance for armor piercing ability for weapons 
Armor piercing value now added for weapons and consumables.  It is a value to subtract from armor protection.  The total AP value is the sum of both the weapon and consumable AP values (not to exceed the primary armor value).  The. AP inputs are forced to be integers on their respective item sheets.
No
> feat: add armor piercing feature on weapons and consumables

- src/module/entities/TwodsixActor.ts
- src/module/handlebars.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/actors/ship-sheet.html
- static/templates/items/component-sheet.html
weight is now total weight for all units
power is total power for all units - power gen is negative.
Features and Fixes
Folks want ship component lists that are more useful
> - Component power and weight list on ship actor is for all units - not per unit
> - Short description deleted from single-line list view
> - Checkbox to designate whether power is generated or consumed by component.
> - If a component generates power, its power value is prefixed by a '+' on the list
> -  Checkbox to designate whether fuel …
> fix: revise ship component listing

- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/npc-sheet.html
bug fix
NPC sheet image does not display tall and narrow images correctly
Correct sizing of images
No
> fix: NPC image aspect ratio

- src/module/sheets/AbstractTwodsixItemSheet.ts
- static/templates/items/armor-sheet.html
Bug Fix
Cutting and pasting into contenteditable text fields results in formatted text inconsistent with Twodsix style 
Cutting and pasting into a conteneditable is forced to plain text.
No
> force cut and paste for contenteditables to be plain text

- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/templates/actors/actor-sheet.html
Option to show icons instead of text for biographical information
feature
biographical information for actor sheet uses text or icons depending lifeblood/stamina settings.
Add display option to force icons over text.
No
> feat: add option to show icons in bio

- src/module/entities/TwodsixItem.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/ship/ship-components-single.html
feature
Can't roll from valid damage value on ship component listing.
No way to change damage roll when clicking on actor sheet
Allows damage roll and adds check for valid formula.
Prompts to confirm/change Roll formula.
Respects shift click function.
No
> feat: add damage rolls on ship actor sheet

- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/items/component-sheet.html
feature
Hits to components must be entered on component data sheet.
For the component single row listing on ship sheet, buttons have been added to adjust the hits without having to open the component sheet.  Also, added a ruleset setting for maximum component hits where the item is destroyed.  Default is three.  And, when this number of hits is reached, the component status is automatically set to destroyed.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
> feat: add buttons to component hits list

- src/module/entities/TwodsixActor.ts
- static/templates/items/component-sheet.html
fix
When specifying a hull component that changes the base hull weight by a percentage, the calculations don't work.
Allow a hull component to be a percentage of the hull value.
The base hull value MUST be a value times the weight (e.g. per hull ton).
> fix: unable to set hull component as pct of hull value

- src/module/utils/TwodsixShipActions.ts
bug fix
When specifying a skill for ship actions, a '/' must terminate the skill name 
Skill name no longer needs slash if just specifying a skill and no modifiers
No
> fix: specifying skills for ship actions

- static/templates/actors/npc-sheet.html
bug fix
Extra comma shown on skill list if unskilled last skill item
Do not show extra comma
No
> fix: get rid of extra comma on npc skill list

- static/styles/twodsix.css
Delete forced !important from p style to allow for custom fonts
fix
bug fix
paragraph font restricted to system style
don't force font or background style
No
> Delete important from p style

- src/module/config.ts
- src/module/entities/TwodsixActor.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/items/component-sheet.html
bug fix
Can't specify fixed hull cost for baseline hull component
Allow three options for base hull: MCr/unit MCr/hull ton, MCr/component ton.  Note that MCr/Hull and MCr/component are the same - both kept for backwards compatibility.
No
> fix: allow more pricing options for hull component

- src/module/entities/TwodsixActor.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/ship/ship-components-single.html
- static/templates/items/armor-sheet.html
- static/templates/items/augment-sheet.html
- static/templates/items/component-sheet.html
- static/templates/items/consumable-sheet.html
- static/templates/items/equipment-sheet.html
- static/templates/items/item-sheet.html
- static/templates/items/junk-sheet.html
- static/templates/items/parts/common-parts.html
- static/templates/items/parts/reference-footer.html
- static/templates/items/ship_position-sheet.html
- static/templates/items/skills-sheet.html
- static/templates/items/storage-sheet.html
- static/templates/items/tool-sheet.html
- static/templates/items/trait-sheet.html
- static/templates/items/weapon-sheet.html
feature update
Item sheets display labels and data on separate lines making the item sheet long
Short descriptions are mainly unused except for traits
#874 
display item label and data on a single line
remove short descriptions from sheets except for traits
No
> feat: improve item sheet layouts

- src/module/hooks/showWoundIcons.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
fix
onTokenUpdate uses old argument references
ship action skill rolls don't reference position in flavor
Use correct argument references of onTokenUpdate
add reference to position in flavor
No
> fix: bad token update arguments and add flavor to ship skill rolls

- src/module/config.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/template.json
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
- static/templates/items/component-sheet.html
feature
max carry weight must be manually entered
no range for ship armament components
provide formula input and calc max carry weight
range field for armaments
no
> feat: add max encumbrance calc for traveller and range field for armament components 

- src/migrations/2022_4_27_09_05_00_fix_move_units.ts
- src/module/config.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-bgi-cd.html
- static/templates/actors/parts/actor/actor-bgi-std.html
Bug fix
Movement units use incorrect key
Fix the reference and migrate to correct key
Yes, will change unit reference for all traveller actors.  Some conversions may not work correctly.
> fix: movement units

- src/module/config.ts
- src/module/entities/TwodsixActor.ts
- src/module/hooks/dragRulerIntegration.ts
- src/module/settings/DisplaySettings.ts
- src/module/settings/RulsetSettings.ts
- static/lang/en.json
feature
Can't use module drag ruler
No setting for default movement and units
Drag ruler now supported with option encumbrance calc
Default movement and units settings are applied to new travellers.
No
> feat: drag ruler integration

- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/ship/ship-state-grid.html
feature
Core ship sheet doesn't distinguish between refined and unrefined fuel
Can toggle file bar to switch between refined and unrefined label
No
> fix: toggle fuel type

- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/utils/TwodsixShipActions.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/templates/chat/damage-message.html
bug fixes
No way to prompt for ship action rolls using chat roll
Alignment error for dice on actor sheet
Dice roll for ship weapons damage roll not shown
Component dice modifier not included in ship weapons rolls
No radiation damage rolls
Try to link dropped item to Untrained if the associated skill doesn't exist
Fix the above
No
Probably should move damage to an …
> Fix: roll settings for ship actions

- src/module/handlebars.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/items/skills-sheet.html
feature
No way to track training
Add a training notes field and indicator on skills list.  Indicator is based on a fraction entered somewhere in the new Training Notes field (e.g. 1/4).  It defaults to 50% if no fraction found.
> feat: add training notes field and indicator

- src/module/config.ts
- src/module/settings/RulsetSettings.ts
- src/module/utils/TwodsixShipActions.ts
- src/types/twodsix.d.ts
- static/lang/en.json
feature
Ship weapon rolls do not have option to include effect with damage roll
New ruleset setting now provides ability to include the effect with damage roll
No
> feat: add option to include effect with ship weapon damage

- src/module/hooks/dropItemOnToken.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
bug fix
Skills can't be dropped with a level (value >=0)
level of dropped skill is preserved if >= 0
No
> fix: allow skills to be dropped with level if >=0

- src/module/utils/TwodsixShipActions.ts
bug fix
When using fire weapons for non-armament component error message occurs that no valid damage field.
Do not auto roll damage for non armament components.
No
> fix: don't auto roll damage for components without damage field

- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/ship/ship-components-single.html
bug fix:
Damage and hits combined into one field cause some rows to be double height
Split damage and hits listings
No
> fix: component list single line layout

- src/module/entities/TwodsixActor.ts
- src/module/hooks/showWoundIcons.ts
- src/module/utils/actorDamage.ts
Bug fix
CE-like rules setting cause unconsciousness saves to be rolled twice if multiple characteristics are damaged.
CE should not roll for unconsciousness
CLU not specified
OTHER follows no wounded scheme
Only one roll now by making a single update to actor - not one for each characteristic
CE does not roll for unconsciousness
CLU included in settings
OTHER behaves like CE
No
* **Other …
> fix: wounded rolls for CE

- src/module/config.ts
- src/module/handlebars.ts
- src/module/hooks/renderChatMessage.ts
- src/module/settings/RulsetSettings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/chat/throw-dialog.html
feature
Must make manual rolls for timeframe associated with skill rolls
option to add timeframe to rolls included
No
> feat: add timeframe option to skill rolls

- src/module/entities/TwodsixActor.ts
- src/module/hooks/showWoundIcons.ts
- src/module/settings/DisplaySettings.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/utils/actorDamage.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/npc-sheet.html
feature & bug fix & refactor
Show wounded relies on token rather than actor.  
CE serious wounds not correct - set for two @ 0 rather than all three with at least 1 damage
No condition icons to overlay actor sheet
Unarmed skill not auto equipped
Dead actor not marked as defeated in combat tracker
Conflict with CUB
Switch functions to purely actor based functions.
CE Serious wounds now displays correctly. Although no way to check for going unconscious the first time.
Add option to display condition icons on …
> fix: showWounds

- src/module/entities/TwodsixItem.ts
- static/templates/actors/parts/actor/actor-consumable.html
bug fix
When reloading, partially filled magazines are lost
Save partially filled magazine / energy cell in consumables inventory
No
> fix: save non-empty magazines when reloading

- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixVehicleSheet.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/vehicle-sheet.html
fix
no vehicle weight or cargo capacity fields
always show unit fields for range and speed
add missing fields
add display option to not show units fields
No
> add cargo capacity and weight fields

- src/module/entities/TwodsixItem.ts
- src/module/hooks/deleteItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- static/template.json
- Fix
- Consumables don't delete correctly from token actors (unlinked)
- Changing parent's equipped state does not change state for attached consumable
- Item sheet doesn't refresh when adding / deleting consumables
- Token actors now work
- Attachments/Consumables change equipped state per parent item
- Item sheet now refreshes
- No, but may need to cycle equipped state to sync
* …
> fix: consumable issues

- src/module/config.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixAnimalSheet.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/templates/actors/parts/actor/actor-bgi-animal.html
bug
fix
No option to change the animal sheet reaction and morale information
Advanced setting added to choose whether to display information
No
> fix: add setting to display reaction and morale on animal sheet

- src/module/settings/DisplaySettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixAnimalSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/sheets/TwodsixVehicleSheet.ts
- src/module/utils/sheetUtils.ts
- src/types/template.d.ts
- static/lang/en.json
- static/lang/es.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/vehicle-sheet.html
- static/templates/items/parts/reference-footer.html
Replace PDFoundry pdf links with native heading drag and drop
Old method of adding pdf links through PDFoundry does not work with v10 (module not updated)
Links to pdf header (rather than a page) or a uri
Old links using pdFoundry are not supported or migrated.
> feat: add item html and pdf links

- src/module/entities/TwodsixActor.ts
- static/templates/items/parts/common-parts.html
bug fix
Movement rate not set to settings if FVTT token defaults used
Unarmed item multiplying when actor duplicated
Skill Roll modifier not visible when item is unattached
Default movement rate always set to advanced settings.
Unarmed item not replicated upon duplication
Skill roll modifier always visible.
No
> Token and actor fixes

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/dropItemOnToken.ts
- src/module/hooks/showStatusIcons.ts
- src/module/settings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/sheetUtils.ts
- src/types/twodsix.d.ts
- static/lang/en.json
bug fix
duplicate items created when dropping on actor sheet
redundant code for drop on token and sheet
unconsciousness rolls don't display a difficulty
increase quantity if name is the same
refactor handling of dropped items to an actor method
show difficulty level for unconsciousness rolls
add option setting to transfer rather than copy when drag-dropping between actors
add transfer dialog
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this …
> feat: Improve drag-drop of items between actors

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
bug fix
Untrained skills (level <0) disappear when dragging and dropping onto actor when hide untrained is set to true
New skills are created at the untrained level
Dropped skills set to a min level of zero if hide untrained setting is true
New skills have default zero value when created with hide untrained true
No
> fix: adding untrained skills

- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-skills.html
Bug Fix
JOAT skill can be dragged and dropped
Prevent drag and dropping of the skill
No
> fix: Quick fix to prevent JOAT from drag and drop

- docs/docs.md
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/showStatusIcons.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/utils/dice.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
- static/templates/actors/parts/actor/actor-npc-consumable.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/actors/parts/vehicle/weapon-components.html
- static/templates/items/consumable-sheet.html
- static/templates/items/parts/consumables-part.html
- static/templates/items/parts/useConsumableForRoll.html
features
-- QOL Challenges exist when using consumables
-- allow magazines to have bonus damage attribute (thanks to @romkre)
-- add code to simplify roll formulas (from dnd5e)
-- add option to make a consumable an attachment (thanks to @DarkBearmancula)
-- add attachment section on actor item page
-- make drag-drop reordering work for consumables
-- fix ship system status indicators when there is more than one component of same subtype
-- fix display of armament components for vehicles
-- check for multiple …
> features: QOL Issues for Consumables

- src/module/sheets/TwodsixShipPositionSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
- src/types/twodsix.d.ts
- [/] We use semantic versioning (https://github.com/semantic-release/semantic-release to be specific), so follow https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- [/] Docs have been added / updated (for bug fixes / features)
Bug fix
Ship positions "XXX/ATR 8+" ignores the ATR and uses the attribute of XXX instead(even for the untrained fallback)
The attribute set in the roll settings has a higher priority than the attribute of the skill
* **Does this PR introduce a …
> fix: ship positions characteristic override

- src/module/sheets/TwodsixShipPositionSheet.ts
- src/module/utils/TwodsixShipActions.ts
- static/lang/en.json
- static/templates/items/ship_position-sheet.html
- [/] We use semantic versioning (https://github.com/semantic-release/semantic-release to be specific), so follow https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
- [/] Docs have been added / updated (for bug fixes / features)
feature
Actions of ship positions allow only 1 named skill
Actions of ship positions allow more than 1 named skill(p.e. "Gunner turret" and "Gunner" if a character didn't learn the specialization)
* **Does this PR introduce a breaking change?** (What …
> feat: Add option for alternative skills in ship positions.

- static/styles/twodsix.css
Fix
Pop-outs from standard menu (e.g. compendiums) have text in default color rather than white (in normal menu)
Popout text to use same white colored text as normal menu list
> fix: text colors on pop-outs

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/settings/DisplaySettings.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixShipActions.ts
- src/types/twodsix.d.ts
- static/lang/en.json
bug fix
can't drop items from compendium
chat rolls for items display skill image not item
no features listed in chat
allow items drops from compendium
chat rolls display item image, if appropriate
New setting to list item features/traits in chat roll
No
> fix: Fix drop from compendium

- src/module/entities/TwodsixActor.ts
- src/module/hooks/showStatusIcons.ts
- src/module/hooks/updateHits.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/actorDamage.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/template.json
- static/templates/chat/throw-dialog.html
bug fix
warning always triggered to decrease endurance / first attribute even if attribute is already damaged
no way to see how player changes hits/stats
if multiple GM's active, damage dialog sides not appear
only trigger warning when no damage to endurance
scrolling text added for healing/damage if actor owner
optional whispered message to chat for damage /healing
allow damage dialog to be seen by all GM's
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
> fix: actor damage dialog and notification issues

- static/templates/actors/parts/ship/ship-state-grid.html
- static/templates/actors/ship-sheet.html
bug fix
ship sheet does not display power management or stats correctly in FVTT default style
Display correctly
> fix: ship layout display in default style

- src/module/sheets/TwodsixItemSheet.ts
Bug Fix
Augment AE disabled by default
Enable augment AE's by default
No
> fix: augment AEs enabled by default

- src/module/entities/TwodsixActor.ts
- static/templates/actors/animal-sheet.html
- static/templates/actors/npc-sheet.html
Bug fixes
Can't drop skill on actor from compendium
Damage roll labels too short on animal and npc sheet
Fix dropping of skill from a compendium
Lengthen damage labels
No
> fix: Fix skill drop and damage labels

- src/module/entities/TwodsixActor.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/utils/TwodsixShipActions.ts
- src/module/utils/sheetUtils.ts
Bug Fixes
- ship skill rolls aren't correct if characteristic is missing
- dropping skill on ship sheet position will duplicate skill roll
- not all drops handle compendiums
- REGEX redone to handle missing characteristic
- Prevent duplication of skill roll
- refactor getItemData to include handling compendium drops
NO
address #1238
> fix: Update ship roll parsing

- src/module/hooks/dragRulerIntegration.ts
- src/module/settings/RulsetSettings.ts
- src/module/utils/TwodsixRollSettings.ts
- src/types/twodsix.d.ts
- static/lang/en.json
Bug fixes
** can't configure drag ruler settings for OTHER ruleset
** bonus damage not applied when rolling from chat card
** new settings for OTHER
** bonus damage now carries forward
No
> fix: Drag ruler settings when using other rules

- src/module/sheets/TwodsixActorSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-items.html
feature
no way to tell which magazine is selected on actor sheet
no easy way to switch consumables on actor sheet
place indicators next to consumable lines to indicate if used for attack roll
add ability to toggle active consumable
no
> feat: add consumable indicators and toggles

- src/module/entities/TwodsixActor.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/system.json
- static/template.json
- static/templates/actors/parts/ship/ship-component-double-item.html
- static/templates/actors/parts/ship/ship-component-single-item.html
- static/templates/items/component-sheet.html
Feature
No ability to count ammo load out for armament components
add new counter field on ship sheet
NO
Fix displacement mass calc to always use value for armament and fuel components
> feat: add armament ammo counter

- src/module/handlebars.ts
- src/module/hooks/chatCard.ts
Bug fixes
- Players can't make chain or opposed rolls from other actor chat cards
- Computers with no attachments break actor sheet
- Players can roll from other player's chat cards
- Handlebar now checks for no attachments first.
> fix: Chain rolls and Computer attachments

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/chatCard.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/module/utils/sheetUtils.ts
- static/lang/en.json
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/templates/items/parts/weapon-sheet-flat.html
- static/templates/items/parts/weapon-sheet-tabbed.html
bug fixes
items without effects cause error on drop
Monks journal Loot sheet doesn't work as it drops itemData and not item object
Monks Journal Items not compatible with AE embedded on items.
MEJ css incompatibilities.
fix above
No
> fix: drop Item without effects and Monk's Journal Loot & Shop Sheets

- src/module/sheets/AbstractTwodsixActorSheet.ts
- static/lang/en.json
Bug fix
Error when dropping actor onto actor sheet in non-Prose mirror field
Create warning that can't drop actor
No
> fix: warning for dropping actor onto non-editing field

- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
bug fixes
format issues for prosemirror interface and dice tray
adjusts formatting to be more in 2d6 style
No
> fix: format updates

- src/module/entities/TwodsixActor.ts
- src/module/hooks/showStatusIcons.ts
- static/templates/actors/parts/actor/actor-effects.html
bug fix
Encumbrance indicator causes errors and can't be deleted on linked actor after change to v11
Fix errors by moving encumbrance check to getData for actor for v11.  May revisit on updates to v11.
yes - encumbrance condition can no longer be deleted.
> fix: temp fixes

- package-lock.json
- package.json
This reverts commit e3d71bdefda288bf800e498ff26df0f5fa52846b.
bug fix
conflict with prettier
Not certain how this got out of sync
> Revert "chore(deps-dev): bump prettier from 2.8.8 to 3.0.0 (#1405)"

- src/module/hooks/diceTrayIntegration.ts
feature
Dice tray buttons are not configured for Twodsix
Add buttons for characteristics and skills to roll pop-up
No
> feat: add dice-tray support

- src/module/entities/TwodsixItem.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/rollItemMacro.ts
- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
- static/system.json
refactor
only run item macro can call prompt for unknown fire mode
style issues with TAH tagify inputs
make it an item method so that Token Action HUD integration can call (rather than duplicate code)
add style fixes for TAH tagify use
yes...Token Action HUD Integration will need to change
> fix: refactor prompt for unknown auto mode

- src/module/entities/TwodsixItem.ts
- src/module/settings.ts
- src/module/settings/AdvancedSettings.ts
- src/module/settings/DisplaySettings.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/system.json
- static/template.json
- static/templates/actors/parts/ship/ship-notes.html
and move weight for worn armor to encumbrance settings
feature
no setting for maximum spell level
no ship references
add new setting to set max spell level for a spell roll
add reference area to ship notes
No
> feat: add maximum spell level setting and ship references

- src/module/handlebars.ts
- src/module/hooks/ready.ts
- src/module/hooks/updateItem.ts
- src/module/settings.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/twodsix.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/system.json
- static/templates/misc/revised-compendium-index-partial.html
- static/templates/misc/revised-document-partial.html
bug fixes, feature
code mirror and TAH interfaces have style clashes with core Twodsix style
no way to see TL in items tab lists
PSI isn't optional if there is no value
fix display issues
add option to show TL for Items Tab
New option to omit PSI display when value is zero
> feat: Misc Display Improvements

- src/module/hooks/ready.ts
- src/module/hooks/setup.ts
- src/module/sheets/AbstractTwodsixItemSheet.ts
- src/twodsix.ts
bug fix
Active Effects for linked actors not active on world load
AE that should be active are active
No
> fix: AE not active for linked actors on load

- src/module/entities/TwodsixItem.ts
- src/module/hooks/tableRolls.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
- src/module/utils/enrichers.ts
- src/module/utils/utils.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
feature
No direct ability to display roll table in Journal Entry
Can't make complex skill rolls without macro
Add @DisplayRollTable enricher. 
Add @SkillRoll enricher. 
Described here: https://github.com/xdy/twodsix-foundryvtt/wiki/Custom-Journal-Page-Enhancers
No
Refactored ship position skill roll code to use parsing across both code bases
> feat: New Enhancer Buttons for Journal pages

- src/module/hooks/chatCard.ts
Bug Fix
Button using `@DisplayTable` in chat doesn't work
Button now executes code from chat.
No
> fix: enable button in DisplayTable for chat messages

- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/enrichers.ts
- src/module/utils/targetModifiers.ts
fix
SkillRoll enricher can't make characteristic checks - must have skill
If 'None' is entered as skill, SkillRoll makes characteristic check, instead.
No
> fix: allow SkillRoll Enricher to make characteristic  checks

- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/enrichers.ts
bug fix
@SkillRoll[None/???] requires the logical short name, not the custom/displayed one.  Also, logical or does not work.
Have @SkillRoll[None/???] work with displayed short label.
The logical or now works with CHR rolls, e.g. @SkillRoll[None/DEX|STR]
> fix: make @SkillRoll always use the displayed char label

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/applyActiveEffects.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
feature and bug fixes
CUSTOM mode for active effects does nothing
Deterministic rolls done with Roll({async: false})
CUSTOM mode now allows for formula effect values
Deterministic rolls done with Roll.safeEval()
> feat: add active effects custom mode

- src/module/entities/TwodsixItem.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/types/template.d.ts
- static/lang/en.json
- static/template.json
- static/templates/items/parts/weapon-parts/weapon-modifiers.html
- static/templates/misc/setting-partial.html
feature
No modifier is applied to ranged weapons used within melee combat range
Add a melee modifier field to weapons and a rules setting to set melee range.
Apply modifier to weapons if within melee range
Using the melee value for range checks against rules setting. It is no longer one adjacent grid unit
> feat: add melee range modifier

- static/templates/items/parts/weapon-sheet-flat.html
bug fix
melee range modifier does not appear on flat weapon sheets
Modifier now appears
No
> fix: missing melee range modifier on flat sheets

- src/migrations/2023_12_30_10_32_refactor_rangeModifier.ts
- src/module/entities/TwodsixItem.ts
- src/types/template.d.ts
- static/template.json
- static/templates/items/parts/weapon-parts/weapon-modifiers.html
- static/templates/items/parts/weapon-sheet-flat.html
feature, bug fix
can only specify integer as melee range modifier
dodge / parry values are positive modifiers
can also specify adv/dis (per settings)
dodge/parry modifiers are negative values
Requires a migration of meleeRangeModifier from int to string on weapons
> feat: add melee range modifier as boon-bane

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/TwodsixShipActions.ts
- src/module/utils/enrichers.ts
- src/module/utils/migration-utils.ts
- src/module/utils/utils.ts
- static/lang/en.json
feature, refactor
Associated skill field for items can only list a single skill name
Allow multiple skills to be listed, separated by pipe.  System selects the best one.
> feat: allow associated skill to list multiple skills

- src/module/settings.ts
- src/module/utils/createItemMacro.ts
- src/module/utils/rollItemMacro.ts
- src/types/twodsix.d.ts
- static/lang/en.json
bug fix
drop item macro on hotbar not robust (uses item.id only, does not update macro if macro by that name exists, duplicates macro on dropbar,
Add optional item.name field as backup lookup, update command if changed, don't add macro to hot bar if already there.
No
> fix: make item macros more robust

- src/module/config.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/diceTrayIntegration.ts
- src/module/settings/RulsetSettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixAnimalSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- src/module/sheets/TwodsixRobotSheet.ts
- src/module/sheets/TwodsixSpaceObjectSheet.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/actorDamage.ts
- src/module/utils/sheetUtils.ts
- src/module/utils/utils.ts
- src/types/template.d.ts
- src/types/twodsix.d.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/template.json
- static/templates/actors/parts/actor/actor-characteristics-table.html
- static/templates/items/skills-sheet.html
feature and refactor
Only 2 alternative char
getDamageTypes can cause circular references 
Add third alt char - visible only with display ALL
move getDamageTypes to sheetUtils
No?
> feat: add third alternate characteristic

- src/module/hooks/dropItemOnToken.ts
- src/module/hooks/itemPilesIntegration.ts
- static/lang/en.json
bug fix
When using item piles module, can't use drop of damage on token.
Allow exception for damageItem drop
Users will need to enable Drag-drop on tokens again if using item piles.
> fix: allow item-piles module to work with damage drop

- src/module/utils/TwodsixDiceRoll.ts
- static/lang/en.json
small feat
no dice information on roll details
add dice data
No
> fix: add dice rolls to details

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/hooks/showStatusIcons.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixItemSheet.ts
- Encumbrance isn't checked when directly changing equipped state on item sheet
- Encumbrance check fires too often
- Check encumbrance state when changing equipped state on item sheet
- Try to reduce the number of encumbrance checks
No
> fix: Try to streamline encumbrance calcs

- src/module/data/character-base.ts
- static/template.json
bug fix
Unable to edit/save traveller biography field
Can edit and save Traveller biography
NO
> fix: can not edit or save  traveller biography field

- src/module/data/vehicles.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/module/sheets/TwodsixShipSheet.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/actor-sheet.html
- static/templates/actors/ship-sheet.html
bug fix
cargo weights aren't visible on ship sheet cargo tab
vehicle shipping size can't be saved
AE edit window tabs mis-aligned
cargo weights are visible
vehicle shipping size in schema
align AE window tabs
No
> fix: missing ship-cargo weights and vehicle-shipping size

- src/module/hooks/activeEffects.ts
bug fix
Custom mode for Active effects don't calculate if initial value zero.
Custom mode for Active effects work correctly if initial value is zero.
> fix: allow zero value for Active Effect Custom

- src/module/settings/DisplaySettings.ts
- src/twodsix.ts
- static/lang/en.json
- static/styles/twodsix.css
fix
Color of the damage fields on actor sheet isn't easily changes and not suited to folks with color issues/
New setting to change the value of these fields.
No
> fix: add option to change the damage-stat-color style

- src/module/entities/TwodsixActor.ts
- src/module/hooks/diceTrayIntegration.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/parts/ship/ship-finance.html
bug fix
If not using prosemirror, finance notes area a single line in height.
Fix box height to a set number of characters
> fix: finance edit box size

- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/system.json
bug fixes
Small image disrupt alignment of Traveller sheet for Firefox
System manifest contains legacy items
User can't adjust default sizes for Traveller sheets
Set a width so that small images display correctly for Firefox
Move legacy items into flags or delete unnecessary ones.
Add setting for default traveller sheet width and height
No
> fix: actor image on traveller sheet too small for firefox

- src/module/config.ts
- src/module/entities/TwodsixItem.ts
bug fixes
double tap adds bonus to attack roll and not damage
have double tap apply correct bonuses
no
> fix: double tap not correct for CD, CLU, CEL

- src/module/settings/DisplaySettings.ts
- src/module/sheets/TwodsixActorSheet.ts
- src/types/twodsix.d.ts
- static/lang/en.json
feature
ALT characteristics are always displayed when enabled
Setting to hide ALT characteristics when value is zero
No
> feat: add setting to omit alt characteristics that are zero

- src/module/settings/DisplaySettings.ts
bug fix
cargo components get reassigned to accommodations when opening
cargo components don't change subtype
no
> fix: missing cargo key in component list

- src/module/config.ts
- src/module/entities/TwodsixActiveEffect.ts
- src/module/entities/TwodsixActor.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/utils/showStatusIcons.ts
bug fix
Encumbrance can be double applied on status change
Encumbrance applied only once
No
> fix:  encumbrance indicator doubling on status change

- src/module/settings/DebugSettings.ts
- src/module/utils/sheetUtils.ts
- src/module/utils/showStatusIcons.ts
- static/lang/en.json
bug fixes
- Problem when dropping item from compendium when item AE setting is not active
- Item AE setting false by default
- No description when rolling consciousness check
- Allow drop and keep AE's when item AE setting off
- Item AE setting default is true
- Add flavor message to unconsciousness rolls.
No
> fix: stop deleting AE's on drop from compendium

- src/module/entities/TwodsixActor.ts
- src/module/entities/TwodsixItem.ts
- src/module/handlebars.ts
- src/module/hooks/addGMControlButtons.ts
- src/module/hooks/diceTrayIntegration.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixVehicleSheet.ts
- src/module/utils/TwodsixDiceRoll.ts
- src/module/utils/TwodsixRollSettings.ts
- src/module/utils/sheetUtils.ts
- src/module/utils/utils.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/templates/actors/animal-sheet.html
- static/templates/actors/battle-sheet.html
- static/templates/actors/npc-sheet.html
- static/templates/actors/parts/actor/actor-bgi-animal.html
- static/templates/actors/parts/actor/actor-bgi-robot.html
- static/templates/actors/parts/actor/actor-consumable.html
- static/templates/actors/parts/actor/actor-npc-consumable.html
- static/templates/actors/parts/actor/actor-skill-item.html
- static/templates/actors/parts/actor/actor-skills.html
- static/templates/actors/parts/common/armament-qty.html
- static/templates/actors/parts/common/component-status.html
- static/templates/actors/parts/common/popup-state.html
- static/templates/actors/parts/ship/ship-component-double-item.html
- static/templates/actors/parts/ship/ship-component-single-item.html
- static/templates/actors/parts/vehicle/vehicle-components.html
- static/templates/actors/robot-sheet.html
- static/templates/items/parts/footer.html
bug fixes and refactor
- Hitting enter on actor sheets defaults to init roll or item sheets to create AE
- Vehicle armaments don't show qty correctly
- battle sheet not using max hit setting
- Vehicle sheet doesn't have popup indicator
- Redundant HTML for component qty, status, and popup state
- Ship component headers not sticky
- error when rolling weapon attack with invalid skill id
- Animals and actors can't have skill AE's
- Stop enter from auto rolling init and creating AE
- Vehicle armaments show qty …
> fix: button changes and component qty fixes

- src/module/entities/TwodsixItem.ts
- src/module/hooks/itemPilesIntegration.ts
- static/lang/en.json
canceled skill rolls now don't display zero psi
bug fix
When cancelling a psi action skill roll, chat displays psi action used for zero points
No chat message
No
> fix: psiPoints show zero on canceled skill roll

- src/module/entities/TwodsixItem.ts
bug fix
Damage roll is made for psionic abilities when roll effect is negative (failure)
No damage roll when effect is negative
No
> fix: damage roll for psionic use when effect negative

- src/module/entities/TwodsixActor.ts
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
bug fix
max encumbrance includes AE STR change when encumbered
AE icons on NPC sheet not left-aligned
Display max encumbrance without AE
AE Icons on NPC left justified
> fix:  max encumbrance so displays correctly when encumbered in CT

- src/module/hooks/addChatContext.ts
bug fix
can't apply damage from chat card context
Applying damage for chat card context works.
No
> fix: make applying damage from chat card context function

- src/module/data/item.ts
- src/module/entities/TwodsixItem.ts
bug fix
drag-dropping weapon resets damage formula to default
drag-drop preserves damage formula
No
> fix: default item damage formula

- src/module/sheets/TwodsixItemSheet.ts
- src/module/utils/ItemTemplate.ts
- static/styles/twodsix.css
- static/styles/twodsix_moduleFix.css
- static/templates/misc/navigation-tabs.hbs
bug fixes
TAH displays groups in columns rather than rows
Using an item with a template causes an error
New tab code for AppV2 is not quite correct
Force TAH to display in rows if using module fix
Gate sheet min and max when using TAH
Refactor tab code for items
NO
> fix: Allow Token Action HUD to work with v13

- src/module/data/character-base.ts
- src/module/data/item-base.ts
- src/module/data/vehicles.ts
bug fix
pdfPager references not showing on newly created items and actors
pdfPager references always have an initial value
> fix: pdfDocument array missing initial empty entry

- src/module/data/characters.ts
- src/module/data/item.ts
- src/module/entities/TwodsixItem.ts
- src/module/settings/DisplaySettings.ts
- src/module/sheets/AbstractTwodsixActorSheet.ts
- src/module/sheets/TwodsixTravellerSheet.ts
- static/lang/en.json
- static/styles/twodsix.css
- static/styles/twodsix_basic.css
- static/styles/twodsix_moduleFix.css
- static/templates/actors/parts/actor/actor-info.hbs
- static/templates/actors/robot-sheet.hbs
- static/templates/items/augment-sheet.hbs
minor feature
- No feature/trait description include for item description send to chat
- Theater Inserts module shows scrollbars on canvas
- Traveller sheet info tab always shows trait AE details for Short Description 
- No Build point / slot tracking for Robots
- Add feature description if feature/trait exists
- Remove Theater Insert scrollbars on canvas
- Add setting to omit the display of AE details for traits
- Add build point and slot usage to augments and robot sheet
* **Does this PR introduce a breaking …
> feat: add optional features trait description

- .gitignore
- CONTRIBUTING.md
Docs update.
The instructions for setting up a development environment using the Node.js version of Foundry are outdated and do not work.
The instructions for setting up a development environment using the Node.js version of Foundry now work for Foundry 13.
* No.
This addresses issue #1841, and to a lesser extent #1842.
> chore: Update development setup instructions
